import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// import Navbar from "./global/components/navbar/navbar";
import Navbar from "./global/components/navbar/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Andy Rubiano",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" />

        <link rel="icon" href="/logo.ico" type="image/x-icon" />
      </head>
      
      <body className={inter.className}>
        <Navbar></Navbar>
        
        <div className="pt-20">
          {children}
        </div>
      </body>
    </html>
  );
}
